### PR TITLE
Minor Fixes for python3.6

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Removing import of dircache as python3.6 no longer supports it.

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@pro-panda @quozl Please have a look. Thanks!

**Comment by quozl** [comment]
Thanks.  Reviewed.

Comment.  While this is potentially useful as a test, either these static bindings for Python 3 should be taken upstream to the Telepathy project, or we should be switching to the GObject Introspection binding, ala TelepathyGLib.  See [Port to TelepathyGLib](https://github.com/orgs/sugarlabs/projects/4).  If there's anything we use that isn't in the binding, we may need to get it added.

**Comment by Aniket21mathur** [comment]
I requested these changes for testing purposes only. I think in the end it would be better to switch to TelepathyGlib. What do you think?

**Comment by quozl** [comment]
Either path is technically viable, in the absence of any surprises, but we have certainly started along the Port to TelepathyGLib path.  You will greatly benefit from reviewing the C code in Telepathy and understanding the relationship between it and the two APIs.

**Comment by Aniket21mathur** [comment]
Thanks. Closing this since I have a fork https://github.com/aniket21mathur/telepathy3 for testing purposes.

**Pull request closed without merging**
